"""empty message

Revision ID: 0015faab6194
Revises: 43083986ae29
Create Date: 2018-03-03 13:39:24.564578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015faab6194'
down_revision = '43083986ae29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_teacher', sa.Column('users', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'charge_teacher', 'users', ['users'], ['id'])
    op.add_column('classesd', sa.Column('grade', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'classesd', 'grades', ['grade'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.drop_column('classesd', 'grade')
    op.drop_constraint(None, 'charge_teacher', type_='foreignkey')
    op.drop_column('charge_teacher', 'users')
    # ### end Alembic commands ###
