"""empty message

Revision ID: 04ff97828365
Revises: 41e29b35f459
Create Date: 2018-03-03 14:45:17.126853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04ff97828365'
down_revision = '41e29b35f459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doorkeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column(u'roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_constraint(u'roles_ibfk_1', 'roles', type_='foreignkey')
    op.drop_column(u'roles', 'user_id')
    op.add_column(u'users', sa.Column('role', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'role')
    op.add_column(u'roles', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'roles_ibfk_1', 'roles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column(u'roles', 'permissions')
    op.drop_column(u'roles', 'default')
    op.drop_table('doorkeepers')
    # ### end Alembic commands ###
