"""empty message

Revision ID: 12afc6e23c20
Revises: 0015faab6194
Create Date: 2018-03-03 13:44:47.912052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12afc6e23c20'
down_revision = '0015faab6194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classesd', sa.Column('charge_teachers', sa.Integer(), nullable=False))
    op.add_column('classesd', sa.Column('grades', sa.Integer(), nullable=False))
    op.add_column('classesd', sa.Column('student', sa.Integer(), nullable=False))
    op.drop_constraint(u'classesd_ibfk_1', 'classesd', type_='foreignkey')
    op.create_foreign_key(None, 'classesd', 'charge_teacher', ['charge_teachers'], ['id'])
    op.create_foreign_key(None, 'classesd', 'grades', ['grades'], ['id'])
    op.create_foreign_key(None, 'classesd', 'students', ['student'], ['id'])
    op.drop_column('classesd', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classesd', sa.Column('grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.create_foreign_key(u'classesd_ibfk_1', 'classesd', 'grades', ['grade'], ['id'])
    op.drop_column('classesd', 'student')
    op.drop_column('classesd', 'grades')
    op.drop_column('classesd', 'charge_teachers')
    # ### end Alembic commands ###
