"""empty message

Revision ID: 1e598d94a8b1
Revises: 801a10680ac1
Create Date: 2018-03-03 13:33:34.736047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e598d94a8b1'
down_revision = '801a10680ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge_teacher', 'users',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('classesd', 'charge_teachers',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('classesd', 'students',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(u'classesd_ibfk_2', 'classesd', type_='foreignkey')
    op.drop_column('classesd', 'grades')
    op.alter_column('students', 'users',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'users',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('classesd', sa.Column('grades', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'classesd_ibfk_2', 'classesd', 'grades', ['grades'], ['id'])
    op.alter_column('classesd', 'students',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('classesd', 'charge_teachers',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('charge_teacher', 'users',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
