"""empty message

Revision ID: 25ecff1065c7
Revises: e29638403381
Create Date: 2018-09-15 20:30:54.617234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ecff1065c7'
down_revision = 'e29638403381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schools_ibfk_1', 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'users', ['school'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_foreign_key('schools_ibfk_1', 'schools', 'schools', ['school'], ['id'])
    # ### end Alembic commands ###
