"""empty message

Revision ID: 27049c94cd82
Revises: efe188be9886
Create Date: 2018-03-04 17:12:50.328333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27049c94cd82'
down_revision = 'efe188be9886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'students_ibfk_3', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'student_parents', ['parent'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(u'students_ibfk_3', 'students', 'users', ['parent'], ['id'])
    op.drop_table('student_parents')
    # ### end Alembic commands ###
