"""empty message

Revision ID: 2d94d226c1bc
Revises: 6b713590862d
Create Date: 2018-09-15 20:27:38.261211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d94d226c1bc'
down_revision = '6b713590862d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('school', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schools', 'schools', ['school'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'school')
    # ### end Alembic commands ###
