"""empty message

Revision ID: 309f6ca2a8ec
Revises: 480f95db643f
Create Date: 2018-03-04 17:52:44.348846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309f6ca2a8ec'
down_revision = '480f95db643f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ask_leave', sa.Column('ask_user', sa.Integer(), nullable=True))
    op.add_column('ask_leave', sa.Column('charge_user', sa.Integer(), nullable=True))
    op.add_column('ask_leave', sa.Column('send_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ask_leave', 'users', ['charge_user'], ['id'])
    op.create_foreign_key(None, 'ask_leave', 'users', ['send_user'], ['id'])
    op.create_foreign_key(None, 'ask_leave', 'users', ['ask_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.drop_column('ask_leave', 'send_user')
    op.drop_column('ask_leave', 'charge_user')
    op.drop_column('ask_leave', 'ask_user')
    # ### end Alembic commands ###
