"""empty message

Revision ID: 34224b5d7057
Revises: 5f229cb494a1
Create Date: 2018-03-03 13:49:12.126784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34224b5d7057'
down_revision = '5f229cb494a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classesd', sa.Column('charge_teachers', sa.Integer(), nullable=False))
    op.add_column('classesd', sa.Column('students', sa.Integer(), nullable=False))
    op.drop_constraint(u'classesd_ibfk_3', 'classesd', type_='foreignkey')
    op.create_foreign_key(None, 'classesd', 'charge_teacher', ['charge_teachers'], ['id'])
    op.create_foreign_key(None, 'classesd', 'students', ['students'], ['id'])
    op.drop_column('classesd', 'student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classesd', sa.Column('student', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.create_foreign_key(u'classesd_ibfk_3', 'classesd', 'students', ['student'], ['id'])
    op.drop_column('classesd', 'students')
    op.drop_column('classesd', 'charge_teachers')
    # ### end Alembic commands ###
