"""empty message

Revision ID: 365684c44da1
Revises: 96a66420b323
Create Date: 2018-03-04 16:00:15.613084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365684c44da1'
down_revision = '96a66420b323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'schools', ['school'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'school')
    # ### end Alembic commands ###
