"""empty message

Revision ID: 3f19b1c1c594
Revises: e12741e6e1f8
Create Date: 2018-06-24 21:49:01.315893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f19b1c1c594'
down_revision = 'e12741e6e1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_teacher', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('charge_teacher', sa.Column('phone', sa.String(length=80), nullable=True))
    op.add_column('student_parents', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('student_parents', sa.Column('phone', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_parents', 'phone')
    op.drop_column('student_parents', 'name')
    op.drop_column('charge_teacher', 'phone')
    op.drop_column('charge_teacher', 'name')
    # ### end Alembic commands ###
