"""empty message

Revision ID: 3fbe95998dba
Revises: 
Create Date: 2018-03-03 13:21:10.727728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fbe95998dba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    op.drop_table('charge_teacher')
    op.drop_table('students')
    op.drop_table('system_versions')
    op.drop_table('classesd')
    op.drop_table('grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('classesd',
    sa.Column('1', mysql.MEDIUMINT(display_width=9), autoincrement=False, nullable=False),
    sa.Column('gradesd', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('system_versions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('summary', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('context', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('number', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['users'], [u'users.id'], name=u'students_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('charge_teacher',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('number', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['users'], [u'users.id'], name=u'charge_teacher_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('static', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
