"""empty message

Revision ID: 41e29b35f459
Revises: 982802de2639
Create Date: 2018-03-03 13:54:50.734991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e29b35f459'
down_revision = '982802de2639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wechat_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wechat_id')
    # ### end Alembic commands ###
