"""empty message

Revision ID: 43083986ae29
Revises: d782dca5d321
Create Date: 2018-03-03 13:36:22.854589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43083986ae29'
down_revision = 'd782dca5d321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('users', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'users')
    # ### end Alembic commands ###
