"""empty message

Revision ID: 480f95db643f
Revises: b1c0f5609cc6
Create Date: 2018-03-04 17:49:21.256985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480f95db643f'
down_revision = 'b1c0f5609cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ask_start_time', sa.DateTime(), nullable=True),
    sa.Column('ask_end_time', sa.DateTime(), nullable=True),
    sa.Column('charge_time', sa.DateTime(), nullable=True),
    sa.Column('charge_state', sa.Integer(), nullable=True),
    sa.Column('why', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ask_leave')
    # ### end Alembic commands ###
