"""empty message

Revision ID: 596354c8f18a
Revises: b98e4c8db8ed
Create Date: 2018-03-04 16:51:10.587852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '596354c8f18a'
down_revision = 'b98e4c8db8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_teacher', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint(u'charge_teacher_ibfk_1', 'charge_teacher', type_='foreignkey')
    op.create_foreign_key(None, 'charge_teacher', 'users', ['user'], ['id'])
    op.drop_column('charge_teacher', 'users')
    op.add_column('students', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint(u'students_ibfk_2', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user'], ['id'])
    op.drop_column('students', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(u'students_ibfk_2', 'students', 'users', ['users'], ['id'])
    op.drop_column('students', 'user')
    op.add_column('charge_teacher', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'charge_teacher', type_='foreignkey')
    op.create_foreign_key(u'charge_teacher_ibfk_1', 'charge_teacher', 'users', ['users'], ['id'])
    op.drop_column('charge_teacher', 'user')
    # ### end Alembic commands ###
