"""empty message

Revision ID: 5f229cb494a1
Revises: c0f5367fd683
Create Date: 2018-03-03 13:46:50.788484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f229cb494a1'
down_revision = 'c0f5367fd683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classesd', sa.Column('student', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'classesd', 'students', ['student'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classesd', type_='foreignkey')
    op.drop_column('classesd', 'student')
    # ### end Alembic commands ###
