"""empty message

Revision ID: 6597fae10131
Revises: 65048de1ebec
Create Date: 2018-09-16 00:46:14.107664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6597fae10131'
down_revision = '65048de1ebec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_teacher', sa.Column('tmp_classes_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge_teacher', 'tmp_classes_id')
    # ### end Alembic commands ###
