"""empty message

Revision ID: 68a9d6467a83
Revises: 2d94d226c1bc
Create Date: 2018-09-15 20:28:19.019679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68a9d6467a83'
down_revision = '2d94d226c1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('schools_ibfk_1', 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'schools', ['user'], ['id'])
    op.drop_column('schools', 'school')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('school', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_foreign_key('schools_ibfk_1', 'schools', 'schools', ['school'], ['id'])
    op.drop_column('schools', 'user')
    # ### end Alembic commands ###
