"""empty message

Revision ID: 69bdd979a260
Revises: 3f19b1c1c594
Create Date: 2018-09-13 21:19:34.981603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bdd979a260'
down_revision = '3f19b1c1c594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_teacher', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('charge_teacher', sa.Column('id_number', sa.String(length=80), nullable=True))
    op.add_column('student_parents', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('student_parents', sa.Column('child_name', sa.String(length=80), nullable=True))
    op.add_column('student_parents', sa.Column('child_number', sa.String(length=80), nullable=True))
    op.add_column('student_parents', sa.Column('id_number', sa.String(length=80), nullable=True))
    op.add_column('student_parents', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_parents', 'schools', ['school_id'], ['id'])
    op.add_column('students', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('students', sa.Column('id_number', sa.String(length=80), nullable=True))
    op.add_column('students', sa.Column('patriarch_name', sa.String(length=80), nullable=True))
    op.add_column('students', sa.Column('patriarch_phone', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(length=50), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('students', 'phone')
    op.drop_column('students', 'patriarch_phone')
    op.drop_column('students', 'patriarch_name')
    op.drop_column('students', 'id_number')
    op.drop_column('students', 'address')
    op.drop_constraint(None, 'student_parents', type_='foreignkey')
    op.drop_column('student_parents', 'school_id')
    op.drop_column('student_parents', 'id_number')
    op.drop_column('student_parents', 'child_number')
    op.drop_column('student_parents', 'child_name')
    op.drop_column('student_parents', 'address')
    op.drop_column('charge_teacher', 'id_number')
    op.drop_column('charge_teacher', 'address')
    # ### end Alembic commands ###
