"""empty message

Revision ID: 6b713590862d
Revises: 86bbc4263684
Create Date: 2018-09-15 19:31:14.941591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b713590862d'
down_revision = '86bbc4263684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('q_number', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['q_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'q_number')
    # ### end Alembic commands ###
