"""empty message

Revision ID: 826b46810f53
Revises: 8778f6b803ae
Create Date: 2018-03-05 14:52:09.731486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826b46810f53'
down_revision = '8778f6b803ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'ask_leave_ibfk_3', 'ask_leave', type_='foreignkey')
    op.create_foreign_key(None, 'ask_leave', 'students', ['ask_users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.create_foreign_key(u'ask_leave_ibfk_3', 'ask_leave', 'users', ['ask_users'], ['id'])
    # ### end Alembic commands ###
