"""empty message

Revision ID: 84adf899fe5a
Revises: 68a9d6467a83
Create Date: 2018-09-15 20:29:19.154028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84adf899fe5a'
down_revision = '68a9d6467a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schools_ibfk_1', 'schools', type_='foreignkey')
    op.drop_column('schools', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('schools_ibfk_1', 'schools', 'schools', ['user'], ['id'])
    # ### end Alembic commands ###
