"""empty message

Revision ID: 8778f6b803ae
Revises: 309f6ca2a8ec
Create Date: 2018-03-04 18:11:47.289975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8778f6b803ae'
down_revision = '309f6ca2a8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ask_leave', sa.Column('ask_users', sa.Integer(), nullable=True))
    op.add_column('ask_leave', sa.Column('back_leave_time', sa.DateTime(), nullable=True))
    op.add_column('ask_leave', sa.Column('charge_users', sa.Integer(), nullable=True))
    op.add_column('ask_leave', sa.Column('send_users', sa.Integer(), nullable=True))
    op.drop_constraint(u'ask_leave_ibfk_1', 'ask_leave', type_='foreignkey')
    op.drop_constraint(u'ask_leave_ibfk_2', 'ask_leave', type_='foreignkey')
    op.drop_constraint(u'ask_leave_ibfk_3', 'ask_leave', type_='foreignkey')
    op.create_foreign_key(None, 'ask_leave', 'users', ['send_users'], ['id'])
    op.create_foreign_key(None, 'ask_leave', 'users', ['charge_users'], ['id'])
    op.create_foreign_key(None, 'ask_leave', 'users', ['ask_users'], ['id'])
    op.drop_column('ask_leave', 'send_user')
    op.drop_column('ask_leave', 'charge_user')
    op.drop_column('ask_leave', 'ask_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ask_leave', sa.Column('ask_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ask_leave', sa.Column('charge_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ask_leave', sa.Column('send_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.drop_constraint(None, 'ask_leave', type_='foreignkey')
    op.create_foreign_key(u'ask_leave_ibfk_3', 'ask_leave', 'users', ['ask_user'], ['id'])
    op.create_foreign_key(u'ask_leave_ibfk_2', 'ask_leave', 'users', ['send_user'], ['id'])
    op.create_foreign_key(u'ask_leave_ibfk_1', 'ask_leave', 'users', ['charge_user'], ['id'])
    op.drop_column('ask_leave', 'send_users')
    op.drop_column('ask_leave', 'charge_users')
    op.drop_column('ask_leave', 'back_leave_time')
    op.drop_column('ask_leave', 'ask_users')
    # ### end Alembic commands ###
