"""empty message

Revision ID: 96a66420b323
Revises: 
Create Date: 2018-03-04 15:19:06.091908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a66420b323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('context', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('schools', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schools'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('wechat_id', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('charge_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doorkeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classesd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('charge_teachers', sa.Integer(), nullable=True),
    sa.Column('grades', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charge_teachers'], ['charge_teacher.id'], ),
    sa.ForeignKeyConstraint(['grades'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('classesd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classesd'], ['classesd.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('classesd')
    op.drop_table('doorkeepers')
    op.drop_table('charge_teacher')
    op.drop_table('users')
    op.drop_table('grades')
    op.drop_table('system_versions')
    op.drop_table('schools')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
