"""empty message

Revision ID: 982802de2639
Revises: 34224b5d7057
Create Date: 2018-03-03 13:52:04.315873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982802de2639'
down_revision = '34224b5d7057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('schools', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grades', 'schools', ['schools'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_column('grades', 'schools')
    # ### end Alembic commands ###
