"""empty message

Revision ID: a05cea09af5b
Revises: 4d8b12ff30e4
Create Date: 2018-03-03 17:18:43.374697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a05cea09af5b'
down_revision = '4d8b12ff30e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('state', sa.Boolean(), nullable=True))
    op.drop_column('schools', 'static')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('static', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('schools', 'state')
    # ### end Alembic commands ###
