"""empty message

Revision ID: b1c0f5609cc6
Revises: 27049c94cd82
Create Date: 2018-03-04 17:28:22.437751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1c0f5609cc6'
down_revision = '27049c94cd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doorkeepers', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint(u'doorkeepers_ibfk_1', 'doorkeepers', type_='foreignkey')
    op.create_foreign_key(None, 'doorkeepers', 'users', ['user'], ['id'])
    op.drop_column('doorkeepers', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doorkeepers', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doorkeepers', type_='foreignkey')
    op.create_foreign_key(u'doorkeepers_ibfk_1', 'doorkeepers', 'users', ['users'], ['id'])
    op.drop_column('doorkeepers', 'user')
    # ### end Alembic commands ###
