"""empty message

Revision ID: b31ebae727aa
Revises: a05cea09af5b
Create Date: 2018-03-03 18:01:33.718532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31ebae727aa'
down_revision = 'a05cea09af5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('sex', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'sex')
    # ### end Alembic commands ###
