"""empty message

Revision ID: bcceaf2c584b
Revises: 6597fae10131
Create Date: 2018-09-16 01:01:12.832812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcceaf2c584b'
down_revision = '6597fae10131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doorkeepers', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doorkeepers', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doorkeepers', type_='foreignkey')
    op.drop_column('doorkeepers', 'school_id')
    # ### end Alembic commands ###
