"""empty message

Revision ID: c0f5367fd683
Revises: 12afc6e23c20
Create Date: 2018-03-03 13:46:31.675431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0f5367fd683'
down_revision = '12afc6e23c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'classesd_ibfk_1', 'classesd', type_='foreignkey')
    op.drop_constraint(u'classesd_ibfk_3', 'classesd', type_='foreignkey')
    op.drop_column('classesd', 'charge_teachers')
    op.drop_column('classesd', 'student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classesd', sa.Column('student', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('classesd', sa.Column('charge_teachers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'classesd_ibfk_3', 'classesd', 'students', ['student'], ['id'])
    op.create_foreign_key(u'classesd_ibfk_1', 'classesd', 'charge_teacher', ['charge_teachers'], ['id'])
    # ### end Alembic commands ###
