"""empty message

Revision ID: d782dca5d321
Revises: 1e598d94a8b1
Create Date: 2018-03-03 13:34:20.941398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd782dca5d321'
down_revision = '1e598d94a8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'charge_teacher_ibfk_1', 'charge_teacher', type_='foreignkey')
    op.drop_column('charge_teacher', 'users')
    op.drop_constraint(u'classesd_ibfk_1', 'classesd', type_='foreignkey')
    op.drop_constraint(u'classesd_ibfk_3', 'classesd', type_='foreignkey')
    op.drop_column('classesd', 'students')
    op.drop_column('classesd', 'charge_teachers')
    op.drop_constraint(u'students_ibfk_1', 'students', type_='foreignkey')
    op.drop_column('students', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'students_ibfk_1', 'students', 'users', ['users'], ['id'])
    op.add_column('classesd', sa.Column('charge_teachers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('classesd', sa.Column('students', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'classesd_ibfk_3', 'classesd', 'students', ['students'], ['id'])
    op.create_foreign_key(u'classesd_ibfk_1', 'classesd', 'charge_teacher', ['charge_teachers'], ['id'])
    op.add_column('charge_teacher', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'charge_teacher_ibfk_1', 'charge_teacher', 'users', ['users'], ['id'])
    # ### end Alembic commands ###
