"""empty message

Revision ID: e12741e6e1f8
Revises: 8ebd836fe714
Create Date: 2018-05-17 03:16:46.493550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12741e6e1f8'
down_revision = '8ebd836fe714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('img', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'img')
    # ### end Alembic commands ###
