"""empty message

Revision ID: e29638403381
Revises: 84adf899fe5a
Create Date: 2018-09-15 20:29:50.011544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e29638403381'
down_revision = '84adf899fe5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('school', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schools', 'schools', ['school'], ['id'])
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'school')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_2', 'users', 'schools', ['school'], ['id'])
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'school')
    # ### end Alembic commands ###
