"""empty message

Revision ID: efe188be9886
Revises: f2f900bc689d
Create Date: 2018-03-04 17:02:43.087418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe188be9886'
down_revision = 'f2f900bc689d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['parent'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'parent')
    # ### end Alembic commands ###
