"""empty message

Revision ID: f2f900bc689d
Revises: fdcd84cdec43
Create Date: 2018-03-04 17:01:50.180397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2f900bc689d'
down_revision = 'fdcd84cdec43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'students_ibfk_3', 'students', type_='foreignkey')
    op.drop_column('students', 'parent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'students_ibfk_3', 'students', 'users', ['parent'], ['id'])
    # ### end Alembic commands ###
