"""empty message

Revision ID: fdcd84cdec43
Revises: 596354c8f18a
Create Date: 2018-03-04 16:57:47.312722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcd84cdec43'
down_revision = '596354c8f18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['parent'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'parent')
    # ### end Alembic commands ###
